application: psnserverapi
version: 3
runtime: python27
api_version: 1
threadsafe: true

inbound_services:
- warmup

builtins:
- remote_api: on
 
handlers:

- url: /wsdl
  static_dir: wsdl

- url: /.*
  script: PlaystationNetworkAPI_server.application
  
